export interface GalleryItem { id: number; title: string; category: 'dssr' | 'paix' | 'leadership'; categoryLabel: string; section: string; img: string; desc: string; date: string; tag: string; }

export const galleryItems: GalleryItem[] = [
  {
    "id": 1,
    "title": "Déjeuner de cohésion sociale - Vue 1",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/484528667_1076017081234581_5468232618266679322_n.jpg",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 1/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 2,
    "title": "Déjeuner de cohésion sociale - Vue 2",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/484555152_1076017031234586_8611261274879065372_n.jpg",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 2/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 3,
    "title": "Déjeuner de cohésion sociale - Vue 3",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/484783623_1076016857901270_2225617598526822804_n.jpg",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 3/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 4,
    "title": "Déjeuner de cohésion sociale - Vue 4",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/484072428_1076016864567936_3711715331058270339_n_Hke9aN0.jpg",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 4/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 5,
    "title": "Déjeuner de cohésion sociale - Vue 5",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/484091679_1076017064567916_7152508016239654659_n_zvV9l6N.jpg",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 5/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 6,
    "title": "Déjeuner de cohésion sociale - Vue 6",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/484149533_1076016914567931_4185037950618386607_n_p0wZbPv.jpg",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 6/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 7,
    "title": "Déjeuner de cohésion sociale - Vue 7",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/484164263_1076017021234587_6414870807836586091_n_zCxbPU2.jpg",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 7/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 8,
    "title": "Déjeuner de cohésion sociale - Vue 8",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/484191805_1076017091234580_1437664556009335235_n_XBjkrLD.jpg",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 8/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 9,
    "title": "Déjeuner de cohésion sociale - Vue 9",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/484244713_1076016861234603_5269455461605233138_n_ElDnkxg.jpg",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 9/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 10,
    "title": "Déjeuner de cohésion sociale - Vue 10",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/484269729_1076017331234556_6236149164847289170_n_Fh4q1ab.jpg",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 10/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 11,
    "title": "Déjeuner de cohésion sociale - Vue 11",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/484320679_1076016027901353_4951928410946398074_n_uuidePd.jpg",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 11/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 12,
    "title": "Déjeuner de cohésion sociale - Vue 12",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/484342673_1076017034567919_3019854611157333233_n_nQYfxjQ.jpg",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 12/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 13,
    "title": "Déjeuner de cohésion sociale - Vue 13",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/484348678_1076017051234584_137647462155535418_n_kN23w0y.jpg",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 13/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 14,
    "title": "Déjeuner de cohésion sociale - Vue 14",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/484355429_1076017041234585_6011780221015654228_n_0cGgYs9.jpg",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 14/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 15,
    "title": "Déjeuner de cohésion sociale - Vue 15",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/484491957_1076017087901247_335125118563590463_n_RWiaprX.jpg",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 15/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 16,
    "title": "Déjeuner de cohésion sociale - Vue 16",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/484493172_1076017024567920_3280376124762105683_n_aSlWX1A.jpg",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 16/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 17,
    "title": "Déjeuner de cohésion sociale - Vue 17",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/484526147_1076017037901252_8213786220639388458_n_JRhM68I.jpg",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 17/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 18,
    "title": "Déjeuner de cohésion sociale - Vue 18",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/485143467_1076017017901254_1283306627836466384_n.jpg",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 18/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 19,
    "title": "Déjeuner de cohésion sociale - Vue 19",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "https://busolaong.com/mediafiles/galerie/WhatsApp_Image_2025-05-14_%C3%A0_00.32.19_7533ab1e.jpg",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 19/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 20,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 1",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG-20251016-WA0090.jpg",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 1/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 21,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 2",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG-20251016-WA0070.jpg",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 2/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 22,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 3",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG-20251016-WA0059.jpg",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 3/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 23,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 4",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG-20251016-WA0060.jpg",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 4/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 24,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 5",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG-20251016-WA0066.jpg",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 5/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 25,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 6",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG-20251016-WA0073.jpg",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 6/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 26,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 7",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG-20251016-WA0077.jpg",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 7/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 27,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 8",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG-20251016-WA0081.jpg",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 8/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 28,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 9",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG-20251016-WA0083.jpg",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 9/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 29,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 10",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG-20251016-WA0090_zrbKHfy.jpg",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 10/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 30,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 11",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG-20251016-WA0094.jpg",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 11/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 31,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 12",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG-20251016-WA0098.jpg",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 12/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 32,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 13",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG-20251016-WA0102.jpg",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 13/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 33,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 14",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG-20251016-WA0103.jpg",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 14/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 34,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 15",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG-20251017-WA0103.jpg",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 15/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 35,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 16",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG-20251017-WA0104.jpg",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 16/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 36,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 17",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG-20251017-WA0105.jpg",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 17/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 37,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 18",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG-20251017-WA0106.jpg",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 18/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 38,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 19",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG-20251017-WA0108.jpg",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 19/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 39,
    "title": "5 ans d&#x27;engagement et d&#x27;Impact - Vue 1",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/IMG-20250322-WA0165.jpg",
    "desc": "Photo prise lors de l'activité: 5 ans d&#x27;engagement et d&#x27;Impact. (Image 1/15)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 40,
    "title": "5 ans d&#x27;engagement et d&#x27;Impact - Vue 2",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/IMG-20250322-WA0167.jpg",
    "desc": "Photo prise lors de l'activité: 5 ans d&#x27;engagement et d&#x27;Impact. (Image 2/15)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 41,
    "title": "5 ans d&#x27;engagement et d&#x27;Impact - Vue 3",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/IMG-20250322-WA0168.jpg",
    "desc": "Photo prise lors de l'activité: 5 ans d&#x27;engagement et d&#x27;Impact. (Image 3/15)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 42,
    "title": "5 ans d&#x27;engagement et d&#x27;Impact - Vue 4",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/IMG-20250322-WA0175.jpg",
    "desc": "Photo prise lors de l'activité: 5 ans d&#x27;engagement et d&#x27;Impact. (Image 4/15)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 43,
    "title": "5 ans d&#x27;engagement et d&#x27;Impact - Vue 5",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/IMG-20250322-WA0178.jpg",
    "desc": "Photo prise lors de l'activité: 5 ans d&#x27;engagement et d&#x27;Impact. (Image 5/15)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 44,
    "title": "5 ans d&#x27;engagement et d&#x27;Impact - Vue 6",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/IMG-20250322-WA0179.jpg",
    "desc": "Photo prise lors de l'activité: 5 ans d&#x27;engagement et d&#x27;Impact. (Image 6/15)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 45,
    "title": "5 ans d&#x27;engagement et d&#x27;Impact - Vue 7",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/IMG-20250322-WA0181.jpg",
    "desc": "Photo prise lors de l'activité: 5 ans d&#x27;engagement et d&#x27;Impact. (Image 7/15)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 46,
    "title": "5 ans d&#x27;engagement et d&#x27;Impact - Vue 8",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/IMG-20250322-WA0182.jpg",
    "desc": "Photo prise lors de l'activité: 5 ans d&#x27;engagement et d&#x27;Impact. (Image 8/15)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 47,
    "title": "5 ans d&#x27;engagement et d&#x27;Impact - Vue 9",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/IMG-20250322-WA0184.jpg",
    "desc": "Photo prise lors de l'activité: 5 ans d&#x27;engagement et d&#x27;Impact. (Image 9/15)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 48,
    "title": "5 ans d&#x27;engagement et d&#x27;Impact - Vue 10",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/IMG-20250322-WA0185.jpg",
    "desc": "Photo prise lors de l'activité: 5 ans d&#x27;engagement et d&#x27;Impact. (Image 10/15)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 49,
    "title": "5 ans d&#x27;engagement et d&#x27;Impact - Vue 11",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/IMG-20250322-WA0188.jpg",
    "desc": "Photo prise lors de l'activité: 5 ans d&#x27;engagement et d&#x27;Impact. (Image 11/15)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 50,
    "title": "5 ans d&#x27;engagement et d&#x27;Impact - Vue 12",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/IMG-20250322-WA0200.jpg",
    "desc": "Photo prise lors de l'activité: 5 ans d&#x27;engagement et d&#x27;Impact. (Image 12/15)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 51,
    "title": "5 ans d&#x27;engagement et d&#x27;Impact - Vue 13",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/IMG-20250322-WA0211.jpg",
    "desc": "Photo prise lors de l'activité: 5 ans d&#x27;engagement et d&#x27;Impact. (Image 13/15)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 52,
    "title": "5 ans d&#x27;engagement et d&#x27;Impact - Vue 14",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/IMG-20250322-WA0264.jpg",
    "desc": "Photo prise lors de l'activité: 5 ans d&#x27;engagement et d&#x27;Impact. (Image 14/15)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 53,
    "title": "5 ans d&#x27;engagement et d&#x27;Impact - Vue 15",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/IMG-20250322-WA0268.jpg",
    "desc": "Photo prise lors de l'activité: 5 ans d&#x27;engagement et d&#x27;Impact. (Image 15/15)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 54,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 1",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG_1150.JPG",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 1/29)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 55,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 2",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG_1158.JPG",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 2/29)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 56,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 3",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG_1198.JPG",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 3/29)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 57,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 4",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG_1217.JPG",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 4/29)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 58,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 5",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG_1248.JPG",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 5/29)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 59,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 6",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG_1260.JPG",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 6/29)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 60,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 7",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG_9311.jpg",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 7/29)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 61,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 8",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG_9318.jpg",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 8/29)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 62,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 9",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG_9339.jpg",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 9/29)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 63,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 10",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/7.JPG",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 10/29)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 64,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 11",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/17.JPG",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 11/29)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 65,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 12",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/21.JPG",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 12/29)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 66,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 13",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/22.JPG",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 13/29)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 67,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 14",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/26.JPG",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 14/29)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 68,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 15",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/27.JPG",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 15/29)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 69,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 16",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/31.JPG",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 16/29)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 70,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 17",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/32.JPG",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 17/29)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 71,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 18",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/34.JPG",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 18/29)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 72,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 19",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/40.JPG",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 19/29)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 73,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 20",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/42.JPG",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 20/29)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 74,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 21",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG_1356.JPG",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 21/29)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 75,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 22",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG_1360.JPG",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 22/29)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 76,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 23",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG_1361.JPG",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 23/29)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 77,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 24",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG_1364.JPG",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 24/29)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 78,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 25",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG_1373.JPG",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 25/29)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 79,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 26",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG_1471.JPG",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 26/29)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 80,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 27",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG_1496.JPG",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 27/29)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 81,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 28",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG_1503.JPG",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 28/29)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 82,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 29",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/gallery/IMG_1504.JPG",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 29/29)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Programme TEDIDJO & RESPECT"
  },
  {
    "id": 83,
    "title": "Déjeuner de plaidoyer - Vue 1",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG_0325.JPG",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 1/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 84,
    "title": "Déjeuner de plaidoyer - Vue 2",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG_0341.JPG",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 2/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 85,
    "title": "Déjeuner de plaidoyer - Vue 3",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG_0351.JPG",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 3/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 86,
    "title": "Déjeuner de plaidoyer - Vue 4",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG_0357.JPG",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 4/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 87,
    "title": "Déjeuner de plaidoyer - Vue 5",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG_0373.JPG",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 5/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 88,
    "title": "Déjeuner de plaidoyer - Vue 6",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG_0389.JPG",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 6/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 89,
    "title": "Déjeuner de plaidoyer - Vue 7",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG_0400.JPG",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 7/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 90,
    "title": "Déjeuner de plaidoyer - Vue 8",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG_0479.JPG",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 8/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 91,
    "title": "Déjeuner de plaidoyer - Vue 9",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG_0481.JPG",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 9/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 92,
    "title": "Déjeuner de plaidoyer - Vue 10",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG_0666.JPG",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 10/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 93,
    "title": "Déjeuner de plaidoyer - Vue 11",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG_0667.JPG",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 11/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 94,
    "title": "Déjeuner de plaidoyer - Vue 12",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG_0668.JPG",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 12/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 95,
    "title": "Déjeuner de plaidoyer - Vue 13",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG_0675.JPG",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 13/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 96,
    "title": "Déjeuner de plaidoyer - Vue 14",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG_0699.JPG",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 14/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 97,
    "title": "Déjeuner de plaidoyer - Vue 15",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG_0701.JPG",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 15/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 98,
    "title": "Déjeuner de plaidoyer - Vue 16",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG_0703.JPG",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 16/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 99,
    "title": "Déjeuner de plaidoyer - Vue 17",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG_0720.JPG",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 17/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 100,
    "title": "Déjeuner de plaidoyer - Vue 18",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG_0721.JPG",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 18/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 101,
    "title": "Déjeuner de plaidoyer - Vue 19",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG_0723.JPG",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 19/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 102,
    "title": "Déjeuner de plaidoyer - Vue 20",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG_0724.JPG",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 20/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 103,
    "title": "Déjeuner de plaidoyer - Vue 21",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG_0730.JPG",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 21/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 104,
    "title": "Déjeuner de plaidoyer - Vue 22",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG_0734.JPG",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 22/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 105,
    "title": "Déjeuner de plaidoyer - Vue 23",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG_0735.JPG",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 23/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 106,
    "title": "Bootcamp Immersif - YES 2025 - Vue 1",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG-20250923-WA0043.jpg",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 1/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 107,
    "title": "Bootcamp Immersif - YES 2025 - Vue 2",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG-20250923-WA0044.jpg",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 2/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 108,
    "title": "Bootcamp Immersif - YES 2025 - Vue 3",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG-20250923-WA0045.jpg",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 3/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 109,
    "title": "Bootcamp Immersif - YES 2025 - Vue 4",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG-20250923-WA0046.jpg",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 4/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 110,
    "title": "Bootcamp Immersif - YES 2025 - Vue 5",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG-20250926-WA0003.jpg",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 5/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 111,
    "title": "Bootcamp Immersif - YES 2025 - Vue 6",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG-20250926-WA0004.jpg",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 6/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 112,
    "title": "Bootcamp Immersif - YES 2025 - Vue 7",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG-20250926-WA0005.jpg",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 7/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 113,
    "title": "Bootcamp Immersif - YES 2025 - Vue 8",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG-20250926-WA0006.jpg",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 8/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 114,
    "title": "Bootcamp Immersif - YES 2025 - Vue 9",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG-20250926-WA0008.jpg",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 9/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 115,
    "title": "Bootcamp Immersif - YES 2025 - Vue 10",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG-20250926-WA0009.jpg",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 10/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 116,
    "title": "Bootcamp Immersif - YES 2025 - Vue 11",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG-20250926-WA0010.jpg",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 11/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 117,
    "title": "Bootcamp Immersif - YES 2025 - Vue 12",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG-20250926-WA0011.jpg",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 12/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 118,
    "title": "Bootcamp Immersif - YES 2025 - Vue 13",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG-20250926-WA0012.jpg",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 13/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 119,
    "title": "Bootcamp Immersif - YES 2025 - Vue 14",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG-20250926-WA0013.jpg",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 14/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 120,
    "title": "Bootcamp Immersif - YES 2025 - Vue 15",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG-20250926-WA0014.jpg",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 15/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 121,
    "title": "Bootcamp Immersif - YES 2025 - Vue 16",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG-20250926-WA0015.jpg",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 16/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 122,
    "title": "Bootcamp Immersif - YES 2025 - Vue 17",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG-20250926-WA0016.jpg",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 17/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 123,
    "title": "Bootcamp Immersif - YES 2025 - Vue 18",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG-20250926-WA0017.jpg",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 18/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 124,
    "title": "Bootcamp Immersif - YES 2025 - Vue 19",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG-20250926-WA0018.jpg",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 19/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 125,
    "title": "Bootcamp Immersif - YES 2025 - Vue 20",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG-20250926-WA0019.jpg",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 20/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 126,
    "title": "Bootcamp Immersif - YES 2025 - Vue 21",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG-20250926-WA0020.jpg",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 21/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 127,
    "title": "Bootcamp Immersif - YES 2025 - Vue 22",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG-20250926-WA0022.jpg",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 22/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 128,
    "title": "Bootcamp Immersif - YES 2025 - Vue 23",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/gallery/IMG-20250926-WA0023.jpg",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 23/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Programme YES"
  },
  {
    "id": 129,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 1",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/BUSOLA_30.jpg.jpeg",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 1/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 130,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 2",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/BUSOLA_27.jpg.jpeg",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 2/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 131,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 3",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/BUSOLA_28.jpg.jpeg",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 3/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 132,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 4",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/BUSOLA_11.jpg.jpeg",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 4/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 133,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 5",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/BUSOLA_38.jpg.jpeg",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 5/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 134,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 6",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/BUSOLA_39.jpg.jpeg",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 6/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 135,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 7",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/BUSOLA_42.jpg.jpeg",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 7/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 136,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 8",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/BUSOLA_49.jpg.jpeg",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 8/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 137,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 9",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/BUSOLA_46.jpg.jpeg",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 9/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 138,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 10",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/BUSOLA_14.jpg.jpeg",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 10/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 139,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 11",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/BUSOLA_17.jpg.jpeg",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 11/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 140,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 12",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/BUSOLA_26.jpg.jpeg",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 12/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 141,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 13",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/BUSOLA_37.jpg.jpeg",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 13/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 142,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 14",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/BUSOLA_32.jpg.jpeg",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 14/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 143,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 15",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/BUSOLA_48.jpg.jpeg",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 15/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 144,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 16",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/BUSOLA_21.jpg.jpeg",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 16/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 145,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 17",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/BUSOLA_31.jpg.jpeg",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 17/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 146,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 18",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/BUSOLA_51.jpg.jpeg",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 18/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 147,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 19",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/BUSOLA_5.jpg.jpeg",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 19/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 148,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 20",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/BUSOLA_13.jpg.jpeg",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 20/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 149,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 21",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/BUSOLA_73.jpg.jpeg",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 21/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 150,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 22",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/BUSOLA_25.jpg.jpeg",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 22/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  },
  {
    "id": 151,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 23",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/gallery/BUSOLA_36.jpg.jpeg",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 23/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Vie de l'ONG & Événements"
  }
];
